---
- instrument: BTC-USD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BTC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1410912000
    period2: 1644537600
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 100
    capital: 10000000
    data_format: yahoo_finance
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2 
    overSoldThreshold: 10
    overBoughtThreshold: 90
    data_format: yahoo_finance_data
